---
title: "Test"
author: "Terry"
date: "June 12, 2020"
output: pdf_document
---


```{r}
library("readr")
library("stargazer")
library(plm)
library(sandwich)
library(lmtest)
library(AER)
library(stargazer)
library(readr)

nba <- read.csv("ivnba.csv")
```




```{r}
testiv <- lm(nba$contract_year ~ nba$contract_2018)
```

```{r, results='asis'}
##Testing for Strength of Instrument

testiv <- lm(nba$contract_year ~ nba$contract_2018)

stargazer(linearHypothesis(testiv, "nba$contract_2018 = 0", 
                 vcov = vcovHC, type = "HC1"))
```

```{r ivstrength, results='asis'}

```

```{r test, results='asis'}
ivlmdbo <- ivreg(nba$DEF.Box.Outs ~ nba$contract_year + nba$salary_current
                 + nba$min + nba$age + nba$pos
                 + nba$name + nba$season | nba$contract_2018 + nba$salary_current
                 + nba$min + nba$age + nba$pos
                 + nba$name + nba$season,
                 weights = nba$min)
ivlmobo <- ivreg(nba$OFF.Box.Outs ~ nba$contract_year + nba$salary_current
                + nba$min + nba$age + nba$pos + nba$team
                + nba$name + nba$season | nba$contract_2018 + nba$salary_current
                + nba$min + nba$age + nba$pos + nba$team
                + nba$name + nba$season,
                weights = nba$min)
ivlmbo <- ivreg(nba$Box.Outs ~ nba$contract_year + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season | nba$contract_2018 + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season,
                 weights = nba$min)

stargazer(coeftest(ivlmdbo, vcov. = vcovHC, type = "HC1"), coeftest(ivlmobo, vcov. = vcovHC, type = "HC1"), coeftest(ivlmbo, vcov. = vcovHC, type = "HC1"), dep.var.labels = "Box Out Metrics", covariate.labels = c("Contract Year", "Current Salary", "Average Minutes Played", "Age"), omit=c("pos", "name", "team"))

ivlmws48 <- ivreg(nba$ws_48 ~ nba$contract_year + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season | nba$contract_2018 + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season,
                 weights = nba$min)

ivlmdws <- ivreg(nba$dws ~ nba$contract_year + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season | nba$contract_2018 + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season,
                 weights = nba$min)

coeftest(ivlmdws, vcov. = vcovHC, type = "HC1")

ivlmows <- ivreg(nba$ows ~ nba$contract_year + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season | nba$contract_2018 + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season,
                 weights = nba$min)

coeftest(ivlmows, vcov. = vcovHC, type = "HC1")

ivlmws <- ivreg(nba$ws ~ nba$contract_year + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season | nba$contract_2018 + nba$salary_current
                 + nba$min + nba$age + nba$pos + nba$team
                 + nba$name + nba$season,
                 weights = nba$min)

stargazer(coeftest(ivlmdws, vcov. = vcovHC, type = "HC1"), coeftest(ivlmows, vcov. = vcovHC, type = "HC1"),
          coeftest(ivlmws, vcov. = vcovHC, type = "HC1"),
          coeftest(ivlmws48, vcov. = vcovHC, type = "HC1"),
              dep.var.labels = "Win Share Metrics", covariate.labels = c("Contract Year", "Current Salary", "Average Minutes Played", "Age"), omit=c("pos", "name", "team"))
```

